### ISSUE TITLE
Logstash stop after few seconds

### ISSUE THREAD

**Issue by AntoineLemaire** [docker-library/logstash#59]
I'm trying to use the lastest version:

```
FROM logstash:2.4.0-1
WORKDIR /etc/logstash
COPY ./conf/logstash.conf ./conf.d
CMD ["logstash","agent","-f","/etc/logstash/conf.d/"]
```

With that conf 

```
input {
    gelf {
        codec => "json"
    }
}
output {
    elasticsearch {
        hosts => "es:9200"
        index => "logs"
    }
}
```

after only few seconds of up, 

```
root@4f4312c803c9:/etc/logstash# service logstash status
logstash is not running
```

if I start him again

```
root@4f4312c803c9:/etc/logstash# service logstash start 
logstash started.
root@4f4312c803c9:/etc/logstash# service logstash status
logstash is running
[... 5 secondes ...]
root@4f4312c803c9:/etc/logstash# service logstash status
logstash is not running
```

All my logs in `/var/logs/logstash/` are empty

If I try to launch logstash agent:

```
root@4f4312c803c9:/etc/logstash# logstash agent -f /etc/logstash/conf.d/                                                                                                                                                              
Settings: Default pipeline workers: 4
gelf listener died {:exception=>#<SocketError: bind: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:160:in `bind'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-2.0.7/lib/logstash/inputs/gelf.rb:98:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-2.0.7/lib/logstash/inputs/gelf.rb:77:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:336:in `start_input'"], :level=>:warn}
Pipeline main started
gelf listener died {:exception=>#<SocketError: bind: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:160:in `bind'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-2.0.7/lib/logstash/inputs/gelf.rb:98:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-2.0.7/lib/logstash/inputs/gelf.rb:77:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:336:in `start_input'"], :level=>:warn}
gelf listener died {:exception=>#<SocketError: bind: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:160:in `bind'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-2.0.7/lib/logstash/inputs/gelf.rb:98:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-2.0.7/lib/logstash/inputs/gelf.rb:77:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:336:in `start_input'"], :level=>:warn}
[...same line again and again...]
```

**Comment by yosifkit** [comment]
`service status` will not work in a container. There is no init system running.  The only process in the container is `logstash`.  In other words, if the container is up, logstash is running.

``` console
$ docker run -it --rm --name gelfling logstash -e 'input {        
    gelf {
        codec => "plain"
    }
}       
output {
    elasticsearch {
        hosts => "es.docker:9200"
        index => "logs"
    }
}'
Settings: Default pipeline workers: 8
Pipeline main started
...
$ # new terminal
$ docker exec -it gelfling bash
root@291f1e915dd8:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
logstash     1  3.6  1.1 5127240 362508 ?      Ssl+ 18:16   0:15 /usr/lib/jvm/java-8-openj
root        62  0.5  0.0  21948  3608 ?        Ss   18:23   0:00 bash
root        68  0.0  0.0  19188  2396 ?        R+   18:23   0:00 ps aux
root@291f1e915dd8:/# 
```

**Comment by AntoineLemaire** [comment]
I've not even test if logstash was working or not...
Many thanks for the answer!
