### ISSUE TITLE
logstash:5.1.1-alpine tls not working

### ISSUE THREAD

**Issue by rauizab** [docker-library/logstash#76]
Hi

 For this image "logstash:5.1.1-alpine", applying tls configuration, I get:

```

logstash | 17:04:05.146 [LogStash::Runner] DEBUG logstash.outputs.stdout - config LogStash::Outputs::Stdout/@workers = 1
logstash | 17:04:05.150 [Ruby-0-Thread-3: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:22] DEBUG logstash.agent - starting agent
logstash | 17:04:05.151 [Ruby-0-Thread-3: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:22] DEBUG logstash.agent - starting pipeline {:id=>"main"}
logstash | 17:04:05.171 [[main]-pipeline-manager] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using Log4J as the default logging framework
logstash | 17:04:05.177 [[main]-pipeline-manager] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
logstash | 17:04:05.177 [[main]-pipeline-manager] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
logstash | 17:04:05.192 [[main]-pipeline-manager] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library: netty-tcnative-linux-x86_64.
logstash | java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative-linux-x86_641626956263373779409.so: Error loading shared library libcrypt.so.1: No such file or directory (needed by /tmp/libnetty-tcnative-linux-x86_641626956263373779409.so)
logstash | 	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_111-internal]
logstash | 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_111-internal]
logstash | 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_111-internal]
logstash | 	at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_111-internal]
logstash | 	at java.lang.System.load(System.java:1086) ~[?:1.8.0_111-internal]
```

I think the issue is that he tries to copy  netty-tcnative-linux-x86_64 but he doesnt do it with this image.
With image "logstash:5.1.1" everything works perfect.
I tried to apply this solution https://discuss.elastic.co/t/problem-with-cipher-in-beat-input/67841/4 but without success.

**Comment by rauizab** [comment]
Related to https://github.com/logstash-plugins/logstash-input-beats/issues/159

**Comment by tianon** [comment]
Does it work if you install `libc6-compat` (which appears to be the provider of the `libcrypt.so.1` file; https://pkgs.alpinelinux.org/contents?file=libcrypt.so.1&branch=v3.4&repo=main&arch=x86_64)?

It might also link against other things we can't provide, but that seems like a good place to start. :smile:

**Comment by kyblik** [comment]
Works for me.

**Comment by rauizab** [comment]
Hi @kyblik

Does it work for you with this image "logstash:5.1.1-alpine"? 
Can you provide your os and your logstash configuration? 
That could be of great help for me.

Thanks in advance.

**Comment by kyblik** [comment]
Hi @rauizab,

current `logstash:5.1.1-alpine` does not work for me. But with installing the package mentioned by @tianon it started to work again. Tested on AWS ECS with current amazon linux ami `	ami-ba346ec9`.

Also I am using just simple `file`s in `input` section with no special config.

**Comment by rauizab** [comment]
It worked for me. Thanks.

**Comment by rauizab** [comment]
Without ssl configuration I see the errors in the logs but logstash can still run.
But with ssl active is different. I am using this configuration and I see the errors in the logs and they say that logstash was not able to find the cipher.

```
input {
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "/logstash/logstash.crt"
    ssl_key => "/logstash/logstash.key"
  }
}
```

Logs
```
[2017-01-10T10:21:05,185][DEBUG][io.netty.util.internal.NativeLibraryLoader] -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
[2017-01-10T10:21:05,185][DEBUG][io.netty.util.internal.NativeLibraryLoader] -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
[2017-01-10T10:21:05,204][DEBUG][io.netty.util.internal.NativeLibraryLoader] Unable to load the library: netty-tcnative-linux-x86_64.
java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative-linux-x86_645547790681300638139.so: Error relocating /tmp/libnetty-tcnative-linux-x86_645547790681300638139.so: __isnan: symbol not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_111-internal]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_111-internal]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_111-internal]
	at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_111-internal]
	at java.lang.System.load(System.java:1086) ~[?:1.8.0_111-internal]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:214) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:161) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:325) [netty-all-4.1.3.Final.jar:4.1.3.Final]

```
...
```
2017-01-10T10:21:05,359][DEBUG][io.netty.util.internal.PlatformDependent] -Dio.netty.noPreferDirect: false
[2017-01-10T10:21:05,359][DEBUG][io.netty.util.internal.PlatformDependent] io.netty.maxDirectMemory: 1038876672 bytes
[2017-01-10T10:21:05,377][DEBUG][io.netty.channel.nio.NioEventLoop] -Dio.netty.noKeySetOptimization: false
[2017-01-10T10:21:05,377][DEBUG][io.netty.channel.nio.NioEventLoop] -Dio.netty.selectorAutoRebuildThreshold: 512
[2017-01-10T10:21:05,390][DEBUG][io.netty.handler.ssl.CipherSuiteConverter] Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 => ECDHE-RSA-AES256-GCM-SHA384
[2017-01-10T10:21:05,399][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Cipher `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` is not available>, :backtrace=>["/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:184:in `create_server'", "/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:172:in `register'", "/logstash/logstash-core/lib/logstash/pipeline.rb:353:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `start_inputs'", "/logstash/logstash-core/lib/logstash/pipeline.rb:228:in `start_workers'", "/logstash/logstash-core/lib/logstash/pipeline.rb:183:in `run'", "/logstash/logstash-core/lib/logstash/agent.rb:292:in `start_pipeline'"]}
[2017-01-10T10:21:05,417][DEBUG][logstash.agent           ] Starting puma
[2017-01-10T10:21:05,424][DEBUG][logstash.agent           ] Trying to start WebServer {:port=>9600}
[2017-01-10T10:21:05,426][DEBUG][logstash.api.service     ] [api-service] start
[2017-01-10T10:21:05,481][DEBUG][logstash.instrument.collector] Collector: Sending snapshot to observers {:created_at=>2017-01-10 10:21:05 +0000}
[2017-01-10T10:21:05,505][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-01-10T10:21:06,494][DEBUG][logstash.instrument.collector] Collector: Sending snapshot to observers {:created_at=>2017-01-10 10:21:06 +0000}
[2017-01-10T10:21:07,505][DEBUG][logstash.instrument.collector] Collector: Sending snapshot to observers {:created_at=>2017-01-10 10:21:07 +0000}
[2017-01-10T10:21:08,404][DEBUG][logstash.instrument.periodicpoller.os] PeriodicPoller: Stopping
[2017-01-10T10:21:08,404][DEBUG][logstash.instrument.periodicpoller.jvm] PeriodicPoller: Stopping
[2017-01-10T10:21:08,408][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
[2017-01-10T10:21:08,408][DEBUG][logstash.pipeline        ] Closing inputs
[2017-01-10T10:21:08,408][DEBUG][logstash.inputs.beats    ] stopping {:plugin=>"LogStash::Inputs::Beats"}
[2017-01-10T10:21:08,409][DEBUG][logstash.pipeline        ] Closed inputs

```

**Comment by rauizab** [comment]
Maybe related https://github.com/netty/netty-tcnative/issues/111

**Comment by NetaNir** [comment]
we are having the same problem, using logstash:5.2.0-alpine, from logstash config:
    beats {
      port => 5044
      tags => ["beats"]
      ssl => true
      ssl_certificate => "/cert.pem"
      ssl_key => "/cert.key"
    }

 from the logs: 

`ERROR logstash.agent - Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Cipher `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384` is not available>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:184:in `create_server'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:172:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:358:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:357:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:233:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:188:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:302:in `start_pipeline'"]}`

and the logstash exit. 
when not enabling ssl on the beats input this doesn't happen.

**Comment by disaster37** [comment]
same problem on 5.2.1.

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/logstash/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `logstash` image](https://www.elastic.co/guide/en/logstash/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/logstash/logstash:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Logstash via the [elastic/logstash GitHub repository](https://github.com/elastic/logstash) and the Docker image via the [elastic/logstash-docker GitHub repository](https://github.com/elastic/logstash-docker), as well as community support via its [forums](https://discuss.elastic.co/c/logstash).

Thanks!
